### PR TITLE
Check for archived Contentful campaigns

### LINKED ISSUE #808: GET campaigns response is broken
// 20170308131524
// http://ds-mdata-responder-staging.herokuapp.com/v1/campaigns

{
  "error": {
    "code": 500,
    "message": "expecting an array or an iterable object but got [object Null]"
  }
}

### PR DESCRIPTION
**Pull request by aaronschachter**
#### What's this PR do?
Fixes GET campaigns response when a Contentful campaign has been archived, but still has a published keyword. 

#### How should this be reviewed?
GET /campaigns

#### Any background context you want to provide?
My recommendation is we always keep Campaigns in Contentful published. Regardless -- we want this check to avoid a broken response.

#### Relevant tickets
Fixes #808 

#### Checklist
- [x] Tested on staging: http://ds-mdata-responder-staging.herokuapp.com/v1/campaigns

### CODE REVIEW

File: app/routes/campaigns.js [hunk 1]
```diff
@@ -3,7 +3,7 @@
 const express = require('express');
 const router = express.Router(); // eslint-disable-line new-cap
 const Promise = require('bluebird');
-const Campaign = require('../exceptions/NotFoundError');
+const Campaign = require('../models/Campaign');
```
Comment (sergii-tkachenko) [inline app/routes/campaigns.js]: Wow. Sorry I missed that earlier.

**Review by sergiitk — APPROVED** [review]
👍
