### PR TITLE
Fixes isYesResponse bug from #733

### LINKED ISSUE #738: Signup Broadcast 500 error: getFirstWord is not defined
Responding to a Signup Broadcast results in an error introduced by #733.

* [x] Fix bug
* [ ] Document list of all endpoints / scenarios to fully test all CampaignBot scenarios / responses to avoid missing errors like #736 and this one. Refs #671

### PR DESCRIPTION
**Pull request by aaronschachter**
#### What's this PR do?
* Fixes bug introduced by #733 that throws 500 error upon responding to a Signup Broadcast
* Adds a just a little bit more logging to log when we call `isCommand` and if current request is a response to a Signup Broadcast
* Handles scenario where Signup Broadcast is sent to a User who's already signed up and has a draft Reportback Submission started. Answering Yes would result in the `invalid_zip` response -- instead we send back the next question to ask with the "Picking up where you left off" copy.

#### How should this be reviewed?
* Post to staging ~~`chatbot?broadcast=true`~~ `chatbot` endpoint and include a `broadcast_id` in the request body.
* Verify passing  yes and no responses return either the relevant Signed Up message, or the Signup Broadcast Declined message.

#### Any background context you want to provide?
Think it makes sense to do a minor refactor here -- instead of checking for a `req.query.broadcast` parameter, look for a `req.body.broadcast_id` that gets sent when User is responding to a Mobile Commons broadcast. That would mean we can avoid use of a separate mData for broadcasts entirely, and just use the single Chatbot mData (POST `/v1/chatbot`) for both Chat OIP responses and Broadcast responses.

#### Relevant tickets
Fixes #738

#### Checklist
- [ ] Documentation added for new features/changed endpoints -- list all endpoints to test and scenarios
- [x] Tested on staging.

### CODE REVIEW

**Comment by aaronschachter** [comment]
Makes the change to check for the request `body.broadcast_id` instead of `query.broadcast_id` -- which means we no longer need 2 mData's (one for Chatbot, one for Signup Broadcasts with the query string) -- we can back to using just the 1 Chat mData.

File: app/models/CampaignBot.js [hunk 1]
```diff
@@ -63,16 +63,15 @@ campaignBotSchema.statics.lookupByID = function (id) {
...
-  const logMsg = `campaignbot: ${msgType}`;
+  const logMsg = `campaignbot:${msgType}`;
   logger.info(logMsg);
   stathat(logMsg);
 
   const botProperty = `msg_${msgType}`;
   let msg = this[botProperty];
   const campaign = req.campaign;
   if (!campaign) {
-    stathat('campaignbot: undefined campaign');
```
Comment (aaronschachter) [inline app/models/CampaignBot.js]: See https://github.com/DoSomething/gambit/pull/737/files#r87543988

**Review by sergiitk — APPROVED** [review]
👍
